### ISSUE TITLE
HelloWorld TCP example

### ISSUE THREAD

**Issue by golizheh** [eProsima/FIROS2#12]
Hi,

I just have a question about TCP connection between two PCs.
As I understand I have to use config_tcp.xml, but my question is that, How should I write the IP Address for each of the machines in this file. Can I write it in the following way:

TCPv4_Server: IP_Add_PC1 (It has FIROS2 and ROS2 installed)
TCPv4_Client:  IP_Add_PC2 (Just Fast RTPs is installed)

From PC2 it is needed to run HelloWorldTCP example? and ROS2 is ok to run talker/listener?(I mean in the case of topics)
Is it needed to change another thing in configuration in the Config file?

Thanks and look forward to hearing from you

**Comment by LuisGP** [comment]
Hi @golizheh 

When using TCP you must define a TCP transport (and if you don't want to use the default UDP transport, disable the builtin transports) for both, client and server.

```xml
<useBuiltinTransports>false</useBuiltinTransports>
```

The server only needs a port number, or listening port. If you don't want to attach to all your network interfaces, you can use a whitelist.

```xml
<transport_descriptor>
    <transport_id>TCPv4_Server</transport_id>
    <type>TCPv4</type>
    <wait_negotiation>false</wait_negotiation>
    <listening_ports>
        <port>5100</port>
    </listening_ports>
</transport_descriptor>
```

The clients, will need to know the server's IP to reach it, and its port. This is done through the initial peers.

```xml
<transport_descriptor>
    <transport_id>TCPv4_Client</transport_id>
    <type>TCPv4</type>
    <wait_negotiation>false</wait_negotiation>
</transport_descriptor>
[...]
<initialPeersList>
    <locator>
        <kind>TCPv4</kind>
        <address>127.0.0.1</address>
        <ports_>
            <physical_port>5100</physical_port>
        </ports_>
    </locator>
</initialPeersList>
```

Both participants need to add its transport descriptors in order to use it.

```xml
<!-->Server's participant<-->
<userTransports>
    <transport_id>TCPv4_Server</transport_id>
</userTransports>

<!-->Client's participant<-->
<userTransports>
    <transport_id>TCPv4_Client</transport_id>
</userTransports>
```

In the example scenario, ROS2 and FIROS2 will communicate through UDP, that why the participant profile **ros2** uses the builtin UDP transport.
On the other hand, HelloWorldTCP and FIROS2 will use TCP. HelloWorldTCP will publish and FIROS2 will subscribe. To make things a little less confusing, we usually match TCP servers with RTPS publishers and TCP clients with subscribers, but both concepts are totally independent and a TCP server could be an RTPS subscriber and vice-versa.

HelloWorldTCP Pub ---TCP---> FIROS2 Sub ---> FIROS2 Pub ---UDP---> ROS2 Listener

I hope this helps you to clarify a bit how it works.

**Comment by golizheh** [comment]
Dear @LuisGP 
Thanks for your nice answer to make the work clear.

So I need to put my  client IP address beside (127.0.0.1) through the initial peers.
And Add  my transport descriptors as follow:



<userTransports>
  
  <transport_id>192.168.1.0 (Server Ip Address where FIROS2 and ROS2 is located)</transport_id>

</userTransports>



<userTransports>

    <transport_id>192.168.1.1 (Client IP address where FASTRTPS is located)</transport_id>

</userTransports>

**Comment by LuisGP** [comment]
Not exactly. I'll try to explain the key points:

* The `<transport_id>` label is just an identifier to reference that transport descriptor within the participants.

* The TCP server doesn't need to know anything about the clients.

* The TCP client needs to be able to reach the server, that's why it needs an initial peer with the server's endpoint (IP address + port).

In your scenario, if I understood well:

* The server must configure a TCP transport descriptor with a listening port (for example 5555).

* The client must configure a TCP transport descriptor, without a listening port (it is possible to define listening ports as a client too, so that participant can act as server and client, but typically isn't needed).

* The client must define the initial peer to reach the server, in this example, using your IP:

```xml
    <locator>
        <kind>TCPv4</kind>
        <address>192.168.1.0</address>
        <ports_>
            <physical_port>5555</physical_port>
        </ports_>
    </locator>
```

As you can see, the client's IP (192.168.1.1) isn't needed for anything.

**Comment by golizheh** [comment]
Dear @LuisGP 

Thanks for your help and your answer,
Finally it is Works :+1: 

The Only problem is that it is works in the one way direction. FASTRTPS publish message and ROS2 wil get it.

BUT I also interested in sending message from ROS2 to FastRTPS? (Is it also possible) I think I have to define another config.xml filr and set correct variable.

**Comment by LuisGP** [comment]
Hi @golizheh 

To achieve two-way communication you only have to define a Fast-RTPS publisher and a ROS2 subscriber, in a similar way there are defined in the example a Fast-RTPS subscriber and a ROS2 publisher, and then, define a connector between this new entities:

```xml
[...]
        <publisher profile_name="fastrtps_publisher">
            <topic>
                <name>HelloWorldTopic</name>
                <dataType>HelloWorld</dataType>
            </topic>
            <historyMemoryPolicy>DYNAMIC</historyMemoryPolicy>
        </publisher>

        <subscriber profile_name="ros2_subscriber">
            <topic>
                <name>rt/chatter</name>
                <dataType>std_msgs::msg::dds_::String_</dataType>
            </topic>
            <historyMemoryPolicy>DYNAMIC</historyMemoryPolicy>
        </subscriber>

[...]

    <connector name="domain_change_ros2_to_fastrtps">
        <reader participant_profile="ros2" subscriber_profile="ros2_subscriber"/>
        <writer participant_profile="rtps" publisher_profile="fastrtps_publisher"/>
        <transformation file="build/libuserlib.so" function="transform_to_fastrtps"/>
    </connector>
```

Take into account, you must implement another transformation function to convert the data in the other way, named in the example `transform_to_fastrtps`. You can define it reusing the same transformation library.

You should also define a mechanism to drop the messages you will receive from your own publishers, like filtering by participant identifier.

**Comment by golizheh** [comment]
<is>
    <topic_types>
        <type name="HelloWorld">
            <participants>
                <participant name="rtps"/>
            </participants>
        </type>
        <type name="std_msgs::msg::dds_::String_">
            <participants>
                <participant name="ros2"/>
            </participants>
        </type>
    </topic_types>

    <profiles>
        <participant profile_name="rtps">
            <rtps>
                <builtin>
                    <domainId>0</domainId>
                </builtin>
            </rtps>
        </participant>

        <participant profile_name="ros2">
            <rtps>
                <builtin>
                    <domainId>0</domainId>
                </builtin>
            </rtps>
        </participant>

<publisher profile_name="fastrtps_publisher">
            <topic>
                <name>HelloWorldTopic</name>
                <dataType>HelloWorld</dataType>
            </topic>
            <historyMemoryPolicy>DYNAMIC</historyMemoryPolicy>
        </publisher>

        <subscriber profile_name="ros2_subscriber">
            <topic>
                <name>rt/chatter</name>
                <dataType>std_msgs::msg::dds_::String_</dataType>
            </topic>
            <historyMemoryPolicy>DYNAMIC</historyMemoryPolicy>
        </subscriber>

   <connector name="domain_change_ros2_to_fastrtps">
        <reader participant_profile="ros2" subscriber_profile="ros2_subscriber"/>
        <writer participant_profile="rtps" publisher_profile="fastrtps_publisher"/>
        <transformation file="build/libuserlib.so" function="transform_to_fastrtps"/>
    </connector>

**Comment by golizheh** [comment]
Hi @LuisGP 

Could you please tell me how the transformation lib is change?

```cpp
extern "C" void USER_LIB_EXPORT transform(SerializedPayload_t *serialized_input, SerializedPayload_t *serialized_output){
    // User types
    std_msgs::msg::dds_::String_ string_data;
    std_msgs::msg::dds_::String_PubSubType string_pst;
    HelloWorld helloworld_data;
    HelloWorldPubSubType helloworld_pst;

    // Deserialization
    helloworld_pst.deserialize(serialized_input, &helloworld_data);

    // Custom transformation
    string_data.data_(helloworld_data.message() + ": " + std::to_string(helloworld_data.index()));
    std::cout << string_data.data_() << std::endl;

    // Serialization
    serialized_output->reserve(string_pst.m_typeSize);
    string_pst.serialize(&string_data, serialized_output);
}
```

 How it  should be changed to the new format for sending information from ROS2 to fastrtps?
And could you please what do you mean by filtering participate identifier?

**Comment by LuisGP** [comment]
> How it should be changed to the new format for sending information from ROS2 to fastrtps?

You must add another function named as indicated in the XML, and perform the inverse conversion:

```cpp
extern "C" void USER_LIB_EXPORT transform_to_fastrtps(SerializedPayload_t *serialized_input, SerializedPayload_t *serialized_output){
	// User types
	std_msgs::msg::dds_::String_ string_data;
	std_msgs::msg::dds_::String_PubSubType string_pst;
	HelloWorld helloworld_data;
	HelloWorldPubSubType helloworld_pst;

	// Deserialization
	string_pst.deserialize(serialized_input, &string_data);

	// Custom transformation
	// To implement, convert string type of format "<Message>: <index>" to HelloWorld type message + index.

	// Serialization
	serialized_output->reserve(helloworld_pst.m_typeSize);
	helloworld_pst.serialize(&helloworld_data, serialized_output);
}
```

The ROS2 type is a string in the format `"<Message>: <index>"`. It must be converted in the custom transformation section into a struct that contains a string member `message` and an integer member `index`.

> And could you please what do you mean by filtering participate identifier?

This feature isn't implemented yet in Integration-Service, so must be done manually. 
In the file `RTPSSubscriber.cpp` in the method `onNewDataMessage` you receive a pointer to the subscriber and you have en structure `m_info` filled after `takeNextData` returns.

If `m_info.sample_identity.writer_guid.guidPrefix` is equals to `sub->getGUID().guidPrefix`, then the received sample comes from yourself and in your case, should be filtered out.

**Comment by golizheh** [comment]
Hi @LuisGP ,
 
I will closs this issue because it is very long, I will explain my problem in the new issue.
