### ISSUE TITLE
Performance and latency

### ISSUE THREAD

**Issue by golizheh** [eProsima/FIROS2#13]
Dear @LuisGP 

I was wondering if you have  already measure the performance and latency of FIROS2 in the network?
I mean if we have installed FASTRTPPS in the cloud server and we have different ROS2 node in the network which have FIROS installed and wants to have communication with each other, how is the performance and delay in the network (request and response delayed)?

With Best Regards
/Golizheh

**Comment by LuisGP** [comment]
Under `Integration-Service/test` you can find some testing and benchmark tools, but we have not test it deeply. Take into account that the bigger performance hit will be the transformation function involved. We tried to avoid copies where possible, but tune in performance wasn't our target at that point of the development.

Best regards.

**Comment by golizheh** [comment]
Thanks
