### ISSUE TITLE
FIROS2 HelloWorldExample

### ISSUE THREAD

**Issue by golizheh** [eProsima/FIROS2#8]
cmake .. -G "Visual Studio 14 2015 Win64"

CMake Error: Could not create named generator Visual Studio 14 2015 Win64

Should I install specific version of Visual Studio?
I have install ROS2 in windows.

Os: Windows 10

**Comment by LuisGP** [comment]
Hi @golizheh 

Which version of Visual Studio are you using?

You only need to install the desired *platform toolset* or modify to command with your installed version, for example:

    cmake .. -G "Visual Studio 15 2017 Win64"

or

    cmake .. -G "Visual Studio 16 2019 Win64"

**Comment by golizheh** [comment]
I have visual studio 2017 community, 
I try it with  cmake .. -G "Visual Studio 15 2017 Win64"
but still error:
CMake Error: Could not create named generator Visual Studio 15 2017 Win64

**Comment by LuisGP** [comment]
After that kind of error, cmake lists the supported generators. Can you paste here that list? Which cmake version are you using?

**Comment by golizheh** [comment]
My cmake version is CMake 2.8.

It does not generate cmake supported list. it is just return back above error.
please ask me if you need more information.

OS: Windows 10

**Comment by LuisGP** [comment]
> My cmake version is CMake 2.8.

That is the problem. CMake 2.8 only supports up to Visual Studio 12.
You should upgrade your CMake, since that version is very old. The current version is 3.15.4.

**Comment by golizheh** [comment]
Thanks for you answer 

After Updating cmake I have get following error:
CMake Error at CMakeLists.txt:15 (find_package):
  By not providing "Findfastcdr.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fastcdr", but
  CMake did not find one.

  Could not find a package configuration file provided by "fastcdr" with any
  of the following names:

    fastcdrConfig.cmake
    fastcdr-config.cmake

  Add the installation prefix of "fastcdr" to CMAKE_PREFIX_PATH or set
  "fastcdr_DIR" to a directory containing one of the above files.  If
  "fastcdr" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred

**Comment by LuisGP** [comment]
FIROS2 depends on Fast-RTPS which depends on Fast-CDR. Do you have an installed Fast-RTPS or are you build FIROS2 from a ROS2 machine?

If you are using a ROS2 machine, you must execute the `local_setup.bat` script in the same terminal you are compiling FIROS2 to allow CMake to find the dependencies.

**Comment by golizheh** [comment]
Thanks The problem was I have not run local_setup.bat.

Thank you very much
