### ISSUE TITLE
Build FIRSOS2 Hello Worl example

### ISSUE THREAD

**Issue by golizheh** [eProsima/FIROS2#9]
After building the solution I have get the following error:

```
C:\dev\ros2-windows\src\ros2\firos2\examples\helloworld\build>cmake --build . --config Release
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/dev/ros2-windows/src/ros2/firos2/examples/helloworld/CMakeLists.txt
  HelloWorld.cxx
  HelloWorldPubSubTypes.cxx
  String_.cxx
  String_PubSubTypes.cxx
  userlib.cpp
C:\dev\ros2-windows\src\ros2\firos2\examples\helloworld\userlib.cpp(23): error C2259: 'std_msgs::msg::dds_::String_PubS
ubType': cannot instantiate abstract class [C:\dev\ros2-windows\src\ros2\firos2\examples\helloworld\build\userlib.vcxpr
oj]
  C:\dev\ros2-windows\src\ros2\firos2\examples\helloworld\userlib.cpp(23): note: due to following members:
  C:\dev\ros2-windows\src\ros2\firos2\examples\helloworld\userlib.cpp(23): note: 'bool eprosima::fastrtps::TopicDataTyp
  e::getKey(void *,eprosima::fastrtps::rtps::InstanceHandle_t *,bool)': is abstract
  C:\dev\ros2-windows\include\fastrtps/TopicDataType.h(82): note: see declaration of 'eprosima::fastrtps::TopicDataType
  ::getKey'
C:\dev\ros2-windows\src\ros2\firos2\examples\helloworld\userlib.cpp(25): error C2259: 'HelloWorldPubSubType': cannot in
stantiate abstract class [C:\dev\ros2-windows\src\ros2\firos2\examples\helloworld\build\userlib.vcxproj]
  C:\dev\ros2-windows\src\ros2\firos2\examples\helloworld\userlib.cpp(25): note: due to following members:
  C:\dev\ros2-windows\src\ros2\firos2\examples\helloworld\userlib.cpp(25): note: 'bool eprosima::fastrtps::TopicDataTyp
  e::getKey(void *,eprosima::fastrtps::rtps::InstanceHandle_t *,bool)': is abstract
  C:\dev\ros2-windows\include\fastrtps/TopicDataType.h(82): note: see declaration of 'eprosima::fastrtps::TopicDataType
  ::getKey'
  Generating Code...
```

**Comment by LuisGP** [comment]
There exists a branch solving that issue. Master branch of FIROS2 uses an old version of Fast-RTPS and the interface of `TopicDataType` changed. 
Try using the branch [feature/TCP_DynTypes](https://github.com/eProsima/FIROS2/tree/feature/TCP_DynTypes).

**Comment by golizheh** [comment]
I try to make it in linux but I have get the follwoing error:

[ 83%] Building CXX object CMakeFiles/userlib.dir/userlib.cpp.o
/home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/userlib.cpp: In function ‘void transform(eprosima::fastrtps::rtps::SerializedPayload_t*, eprosima::fastrtps::rtps::SerializedPayload_t*)’:
/home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/userlib.cpp:23:41: error: cannot declare variable ‘string_pst’ to be of abstract type ‘std_msgs::msg::dds_::String_PubSubType’
  std_msgs::msg::dds_::String_PubSubType string_pst;
                                         ^
In file included from /home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/userlib.cpp:2:0:
/home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/String_PubSubTypes.h:40:19: note:   because the following virtual functions are pure within ‘std_msgs::msg::dds_::String_PubSubType’:
             class String_PubSubType : public eprosima::fastrtps::TopicDataType {
                   ^
In file included from /home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/String_PubSubTypes.h:26:0,
                 from /home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/userlib.cpp:2:
/home/golizheh/ros2_ws/install/fastrtps/include/fastrtps/TopicDataType.h:81:34: note: 	virtual bool eprosima::fastrtps::TopicDataType::getKey(void*, eprosima::fastrtps::rtps::InstanceHandle_t*, bool)
         RTPS_DllAPI virtual bool getKey(void* data, rtps::InstanceHandle_t* ihandle, bool force_md5 
                                  ^
/home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/userlib.cpp:25:23: error: cannot declare variable ‘helloworld_pst’ to be of abstract type ‘HelloWorldPubSubType’
  HelloWorldPubSubType helloworld_pst;
                       ^
In file included from /home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/userlib.cpp:3:0:
/home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/HelloWorldPubSubTypes.h:34:7: note:   because the following virtual functions are pure within ‘HelloWorldPubSubType’:
 class HelloWorldPubSubType : public eprosima::fastrtps::TopicDataType {
       ^
In file included from /home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/String_PubSubTypes.h:26:0,
                 from /home/golizheh/ros2_ws/src/ros2/firos2/examples/helloworld/userlib.cpp:2:
/home/golizheh/ros2_ws/install/fastrtps/include/fastrtps/TopicDataType.h:81:34: note: 	virtual bool eprosima::fastrtps::TopicDataType::getKey(void*, eprosima::fastrtps::rtps::InstanceHandle_t*, bool)
         RTPS_DllAPI virtual bool getKey(void* data, rtps::InstanceHandle_t* ihandle, bool force_md5 
                                  ^
CMakeFiles/userlib.dir/build.make:158: recipe for target 'CMakeFiles/userlib.dir/userlib.cpp.o' failed
make[2]: *** [CMakeFiles/userlib.dir/userlib.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/userlib.dir/all' failed
make[1]: *** [CMakeFiles/userlib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
